### ISSUE TITLE
timeline not reflecting change after click

### ISSUE THREAD

**Issue by alexandersimoes** [data-africa/data-africa-site#90] opened 2017-04-19 19:44 UTC
After clicking to change the year there is no visual feedback.

<img width="578" alt="screen shot 2017-04-19 at 3 41 52 pm" src="https://cloud.githubusercontent.com/assets/252276/25198898/ea36475a-2516-11e7-8756-f8fe8051cc5a.png">

**Comment by davelandry** [comment] 2017-05-09 18:58
duplicate of #83

**Closed as completed by davelandry** 2017-05-09 18:58 UTC
Labels: duplicate
